### ISSUE TITLE
Feature request: add support for multiple test networks

### ISSUE THREAD

**Issue by redragonx** [OpenZeppelin/ethernaut#113]
Hi,

This is related to my problem: https://forum.zeppelin.solutions/t/need-help-with-ethernaut-test-network-ropsten-error/321

It appears that this ropsten test network has been outdated since October 2018 and as a result, nobody can play the game if they have no eth.

What are your thoughts on this?

**Comment by frangio** [comment]
Agree that we should support more test networks. We're no longer using Ropsten, but we're using Rinkeby and it would still be nice to support a couple more for people who may already have test ETH on those other networks.

**Comment by xaler5** [comment]
Closing this as Ethernaut now supports several networks, local network and can be deployed by the user in any preferred network.
