### ISSUE TITLE
Update to Solidity 0.5

### ISSUE THREAD

**Issue by paulinablaszk** [OpenZeppelin/ethernaut#117]
Solidity update to version 0.5 has brought breaking changes. We have to update all contracts to compile with > 0.5

**Comment by frederickalcantara** [comment]
It also wouldn't be a bad idea to write tests for the Solidity code either. It's will be good for testing changes down the road.

**Comment by frederickalcantara** [comment]
Do we have a specific Solidity 5 version that we want to use?

**Comment by paulinablaszk** [comment]
@frederickalcantara What kind of test do you think about?
I've started with "pragma solidity ^0.5.0" because it is actually used in Openzeppelin-solidity and ZeppelinOS smart contracts

**Comment by frederickalcantara** [comment]
Im looking up different types of testing conventions. But I know that TDD is the better way to go in long term, reduces bugs & prevents headaches down the road.
