### ISSUE TITLE
Create Pass/Fail Message similar to Crypto Zombies

### ISSUE THREAD

**Issue by frederickalcantara** [OpenZeppelin/ethernaut#118]
I think there should be sort of way to determine that you completed the level with using a prompt, or a message stating that you passed. Similar to what Crypto Zombies has when you enter in code. You will get a pass or fail prompt.

**Comment by xaler5** [comment]
Ethernat now tells you that with a message in the dev console but also by marking the level as solved and by showing the button "go to the next level"

**Comment by xaler5** [comment]
Fell free to reopen, closing now for inactivity
