### ISSUE TITLE
prevent double button actions

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#12]
eg. submitting a level twice or requesting an instance twice by hitting the buttons consecutively

**Comment by obernardovieira** [comment]
I can do it. Assign to me and put in progress, please.

**Comment by ylv-io** [comment]
Hey, @obernardovieira. Can't assign you but set it in progress. Probably @ajsantander or @martriay can assign you!

**Comment by martriay** [comment]
@obernardovieira I just sent an invite!

**Comment by xaler5** [comment]
Fixed in master
