### ISSUE TITLE
How is Bootstrap implemented?

### ISSUE THREAD

**Issue by scammi** [OpenZeppelin/ethernaut#127]
I'm struggling to see how is bootstrap is implemented since it is only imported on the index.js as bootsrap.css. Which does not include de nav bar class, but Ethernaut uses it none the less. 

For example, Header.js imports: 
```
import React from 'react';
import {connect} from 'react-redux'
import { bindActionCreators } from 'redux'
import * as actions from '../actions'
import * as constants from '../constants'
import { Link, withRouter } from 'react-router'
import ConsoleDetect from '../components/ConsoleDetect'
```
Then it uses bootrap nav:
```
<div className="navbar-collapse collapse">
...
```
So, how is it able to use bootrap with out importing it?
I hope it is not too much of a silly question. What I'm trying to do is add a language dropdown button for the nav bar.

Thank you.

**Comment by xaler5** [comment]
That's because all the components like the Header are mounted inside the index.js where bootstrap is imported. However there's now a language picker :) 

I'm closing this now, fell free to open a Github discussion for any question
