### ISSUE TITLE
Error while trying to install `scrypt` dependency

### ISSUE THREAD

**Issue by NicsTr** [OpenZeppelin/ethernaut#150]
# Description
When trying to build dependency `scrypt`, errors occurs during compilation. Extract from error log:

> make: *** [scrypt.target.mk:129: Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2

It looks like its linked to https://github.com/barrysteyn/node-scrypt/issues/135

Do you have an idea on how I can fix this or manage to run this project without it?

# Steps to reproduce
In a brand new nodeenv:
> git clone git@github.com:OpenZeppelin/ethernaut.git
cd ethernaut
npm install

**Comment by abcoathup** [comment]
Hi @NicsTr,

I am running on Windows Subsystem for Linux with the following versions and I didn't get the `gyp ERR! build error` you are seeing:
```
$ node --version
v10.16.0
$ npm --version
6.12.0
```

Can you advise what operating system (and version) along with node and npm versions you are using?

Have you had issues with installing any other `npm` packages?

Ethernaut is played online: https://ethernaut.openzeppelin.com

What did you want to do with the repository?  (Thinking about how to work around this issue)

**Comment by NicsTr** [comment]
Hi @abcoathup,

I was using `node` v12, now that I downgraded it to v10 it works as expected.

For the record, I try to use the Ethernaut framework to create my own challenges.

Thanks for your time and help.

**Comment by abcoathup** [comment]
Hi @NicsTr,

Glad that you were able to resolve by downgrading node.

FYI: The community is in the process of upgrading from Solidity 0.4 to Solidity 0.5.  The existing contracts have been upgraded but there is an outstanding issue with building the website: https://github.com/OpenZeppelin/ethernaut/pull/123#issuecomment-521896117
