### ISSUE TITLE
Solidity 0.5 Version: Duplicate `Mined transaction` in console after a transaction

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/ethernaut#152]
Duplicate `Mined transaction` in console after a transaction when testing Solidity 0.5 Version of Ethernaut

**💻 Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)
Brave browser on Windows 10

**📝Details**
After submitting a transaction, duplicate `Mined transaction` in console are shown.  Duplicates appear ~ 20 seconds

<img width="275" alt="Etherenaut Solidity 0 5 multiple Mined transaction" src="https://user-images.githubusercontent.com/28278242/69702586-a9f35900-1143-11ea-8d4d-31ce649e9b77.png">

**🔢 Steps to reproduce**

1. Select a level e.g. "Hello Ethernaut"
2. Get New Instance (and submit transaction)
3. `Mined transaction` will be shown
4. Wait and multiple `Mined transaction` will be shown

**Comment by xaler5** [comment]
This is solved in latest version already in production
