### ISSUE TITLE
Solidity 0.5 Version: MaxListenersExceededWarning

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/ethernaut#153]
`MaxListenersExceededWarning` shown in console when testing Solidity 0.5 Version of Ethernaut

**💻 Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)
Brave browser on Windows 10

**📝Details**
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 data listeners added. Use emitter.setMaxListeners() to increase limit` shown in console.

<img width="277" alt="Etherenaut Solidity 0 5 MaxListenersExceededWarning" src="https://user-images.githubusercontent.com/28278242/69776619-1b3d1580-11f1-11ea-9153-f351bf7ca600.png">

**🔢 Steps to reproduce**
Occurs after a transaction.  Haven't been able to narrow down further.

**Comment by abcoathup** [comment]
Related to open issue: https://github.com/ethereum/web3.js/issues/1648

**Comment by xaler5** [comment]
Deprecated
