### ISSUE TITLE
Solidity 0.5 Version: Re-entrancy outdated advice

### ISSUE THREAD

**Issue by bergarces** [OpenZeppelin/ethernaut#154]
:computer: **Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)

:memo: **Details**
After finishing the Re-entrancy level (10) in Ethernaut, a tip appears suggesting to use _transfer_ to move funds out of the contract.

As per [Steve Marx's recent blog post](https://diligence.consensys.net/blog/2019/09/stop-using-soliditys-transfer-now/) and [your own analysis of contracts affected by Istanbul](https://forum.openzeppelin.com/t/openzeppelin-upgradeable-contracts-affected-by-istanbul-hardfork/1616), I believe that a word of warning should be given against transfer/send, and instead provide advice on the [Checks-Effects-Interactions pattern](https://solidity.readthedocs.io/en/develop/security-considerations.html?highlight=check%20effects#use-the-checks-effects-interactions-pattern) and other solutions such as [ReentrancyGuard](https://docs.openzeppelin.com/contracts/2.x/api/utils#ReentrancyGuard).

:1234: **Steps to reproduce**
Complete Re-entrancy level (10) of Ethernaut with Solidity 0.5.

**Comment by xaler5** [comment]
Closing because fixed
