### ISSUE TITLE
Solidity 0.5 Version: Elevator outdated advice

### ISSUE THREAD

**Issue by bergarces** [OpenZeppelin/ethernaut#155]
:computer: **Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)

:memo: **Details**
After finishing the Elevator level (11) in Ethernaut, a tip appears stating that solidity does nothing to prevent a view function from modifying the state.

According to the latest [Solidity documentation](https://solidity.readthedocs.io/en/develop/contracts.html#view-functions), using Byzantium or a newer EVM version for the compiler (which is already the default) will use the opcode STATICCALL for view functions, which enforces the state to stay unmodified.

:1234: **Steps to reproduce**
Complete Elevator level (11) of Ethernaut with Solidity 0.5.

**Comment by xaler5** [comment]
Closing because fixed
