### ISSUE TITLE
Solidity 0.5 Version: Shop - Out of gas

### ISSUE THREAD

**Issue by bergarces** [OpenZeppelin/ethernaut#156]
:computer: **Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)

:memo: **Details**
When attempting to solve the Shop level (21). Once taken into account the Istanbul hard fork and the introduction of [EIP-1884](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1884.md) (which is already active in Ropsten), 3000 gas seems to be insufficient to implement the Buyer.price() due to SLOAD price increase from 200 to 800.

Moreover, if the goal of the challenge is to return different results depending on the value of Shop.isSold instead of saving a flag in storage, forwarding gas is no longer required, as [a view function will now use STATICCALL if the target EVM version of the compiler is Byzantium or newer](https://solidity.readthedocs.io/en/develop/contracts.html#view-functions).

:1234: **Steps to reproduce**
Attempt to solve Shop level (21) of Ethernaut with Solidity 0.5.

**Comment by abcoathup** [comment]
@IvanZakharov what are your thoughts on this?

**Comment by bergarces** [comment]
In retrospective. I think I was wrong suggesting that forwarding gas is no longer required, as even if it can't be used to modify storage any longer, the attacker could use gasleft() to determine which result to return.

**Comment by STYJ** [comment]
I believe this is still an issue. I've tried it with a solution that returns a value depending on what value `isSold` is i.e. I'm not even modifying the state so the `STATICCALL` is not an issue for me. 

`contract AttackShop is Buyer {
    Shop public shop;
    
    constructor(Shop _shop) public {
        shop = _shop;
    }
    
    function buy() public {
        shop.buy();
    }

    function price() public view override returns(uint) {
        return shop.isSold() ? 1 : 101;
    }
}`

<img width="756" alt="Screenshot 2020-04-05 at 3 48 36 PM" src="https://user-images.githubusercontent.com/17739166/78469563-f33c6080-7754-11ea-9d9e-76a5949eb029.png">

As you can see from the image above, calling the `price()` function as is will cost approx 3.7k+ gas. If I modify the Shop contract and increase gas to 3.8k from 3k, I would pass this level.

**Comment by sacredwx** [comment]
same here, the gas is just (a little) insufficient for the solution of the level

**Comment by smessmer** [comment]
It is still solvable. Solution (SPOILERS!): https://pastebin.com/4G4xuUDn

**Comment by abcoathup** [comment]
Hi @smessmer,

Thanks for sharing.  You could add your solution to the community solutions: https://forum.openzeppelin.com/t/ethernaut-community-solutions/561

**Comment by arcticmatt** [comment]
@smessmer that's a nice solution, but I don't think using YUL should be necessary to solve this challenge 😛. should be as simple as `shop.isSold() ? 0 : 100`

**Comment by xaler5** [comment]
Closed by https://github.com/OpenZeppelin/ethernaut/pull/305
