### ISSUE TITLE
Solidity 0.5 Version: Alien Codex - Requesting new instance loop

### ISSUE THREAD

**Issue by bergarces** [OpenZeppelin/ethernaut#157]
:computer: **Environment**
Solidity 0.5 Version of Ethernaut (https://solidity-05.ethernaut.openzeppelin.com/)
Ubuntu 19.10
Chrome Version 78.0.3904.108 (Official Build) (64-bit)
MetaMask 7.6.1

:memo: **Details**
When attempting to get a new instance for the Alien Codex level (19), it seems like a new transaction attempt to create a contract is issued after the previous one is mined successfully.

No other level seems to have this issue.

![EthernautAlienCodexError](https://user-images.githubusercontent.com/1970725/70081398-5fb91e80-1600-11ea-83b6-12cee13c7b52.png)

:1234: **Steps to reproduce**
Press the "Get new instance" button on the Alien Codex level (19) of Ethernaut with Solidity 0.5 and confirm the transaction with MetaMask.

**Comment by abcoathup** [comment]
Thanks, I have the same experience with Alien Codex level.

**Comment by CallMeGwei** [comment]
I'm also having this issue.

**Comment by CallMeGwei** [comment]
## Workaround:

The contract is being created successfully. That fact, however, is not being registered in local storage.

One may manually edit the browser's local storage as a temporary workaround. (Accessing local storage data should be in dev tools.)

![image](https://user-images.githubusercontent.com/34364155/77240964-53aa9a00-6bba-11ea-9fb4-02a7c44548f8.png)

Add the appropriate key:value pair to the `ethernaut_player_data_*VERSION*_*PLAYER*.emittedLevels`
object.

![image](https://user-images.githubusercontent.com/34364155/77240933-d7b05200-6bb9-11ea-89af-0a927c312964.png)

The level key is "0xf0D6F7dA4ed4Ff54761841e497F5aFc795F04688" and the value will be the instance contract address, which can be retrieved from etherscan via the tx hash.

**Comment by sacredwx** [comment]
same here

**Comment by xaler5** [comment]
Is still this an issue ?

**Comment by xaler5** [comment]
works for me 
![image](https://user-images.githubusercontent.com/20795374/209480967-d33664d6-4316-41d7-b402-fa7a67d24465.png)
closing this since we already optimized local storage management . fell free to reopen if still an issue
