### ISSUE TITLE
Solidity 0.5 Version: Levels marked as `Completed` when not attempted

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/ethernaut#160]
Reported by a community member via email:

Levels 10 and 11 show as 'Completed' with blue ticks in front of them when they had not been attempted in the Solidity 0.5 Version. 
Refreshing and hard-refreshing, as well as disabling and re-enabling MetaMask plugin did not resolve.

-----

I have seen something similar previously but haven't been able to reproduce.

**Comment by tinchoabbate** [comment]
Same happened to me, Token and Delegation appeared as completed after I solved Telephone :thinking:

**Comment by abcoathup** [comment]
I now have a number of levels showing as completed:

10. Re-entrancy ✔
11. Elevator ✔
12. Privacy ✔
13. Gatekeeper One
14. Gatekeeper Two ✔
15. Naught Coin ✔
16. Preservation ✔
17. Recovery ✔
18. MagicNumber ✔
19. Alien Codex
20. Denial ✔
21. Shop

**Comment by tinchoabbate** [comment]
I'm trying to track this down.

Completed levels are tracked in LocalStorage (see https://github.com/OpenZeppelin/ethernaut/blob/solidity-05/src/reducers/playerReducer.js#L36-L62). Removing the level from LocalStorage manually puts things back to normal.

The `SUBMIT_LEVEL_INSTANCE` action is triggered here by a listener: https://github.com/OpenZeppelin/ethernaut/blob/solidity-05/src/middlewares/syncPlayerProgress.js#L16-L41. So my first guess is that there's something going on with the event being watched, that may be triggering the action which sets the level as completed. 

By I still haven't figured the _why_.

**Comment by tinchoabbate** [comment]
I seem to have found the culprit. In https://github.com/OpenZeppelin/ethernaut/blob/solidity-05/src/middlewares/syncPlayerProgress.js#L16-L18 we don't seem to be filtering appropriately. According to https://web3js.readthedocs.io/en/v1.2.2/web3-eth-contract.html#contract-events, we should be doing:

```javascript
const log = state.contracts.ethernaut.events.LevelCompletedLog(
    { filter: { player: state.player.address } }
);
```

**Comment by xaler5** [comment]
Deprecated
