### ISSUE TITLE
Get new instance results in error: TypeError: Cannot read property 'address' of undefined

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/ethernaut#170]
Pressing `Get new instance`  button on [Level 0](https://ethernaut.openzeppelin.com/level/0xdf51a9e8ce57e7787e4a27dd19880fd7106b9a5c) results in error in the console:
```
Uncaught (in promise) TypeError: Cannot read property 'address' of undefined
    at t.default (playerReducer.js:30)
    at combineReducers.js:133
    at c (createStore.js:178)
    at middleware.js:22
    at index.js:14
    at collectStats.js:14
    at syncPlayerProgress.js:5
    at setNetwork.js:7
    at setPlayerAddress.js:5
    at activateLevel.js:7
```

This occurs when using MetaMask 8.0.4 on Brave with Ropsten network selected with an account with Ropsten ETH.

First reported in the community forum: https://forum.openzeppelin.com/t/ethernaut-problem-with-player-and-ethernaut-are-not-defined/3347

**Comment by harsh-98** [comment]
I am also getting the same error with new version of the metamask.

**Comment by abcoathup** [comment]
Hi @harsh-98,

You should be able to play Ethernaut.

Thanks to @ayasamind for the PR. 🙏

**Comment by ChrisFenosEY** [comment]
@abcoathup I am getting the same issue. Can use the help() function, but cannot see player or ethernaut.

**Comment by ericnickus** [comment]
Uncaught ReferenceError: ethernaut is not defined. - and I am using rinkeby network on metamask .
