### ISSUE TITLE
Can't complete Alien Codex

### ISSUE THREAD

**Issue by sinsinpurin** [OpenZeppelin/ethernaut#175]
I try ethernaut solc 0.4.24 ver.
It seems that array overflow is not currently possible...

<img width="890" alt="スクリーンショット 2020-08-05 0 12 11" src="https://user-images.githubusercontent.com/40846038/89310947-52cd5d00-d6b0-11ea-9ece-981a8d1732d3.png">

**Comment by abcoathup** [comment]
Hi @sinsinpurin,

We have been able to reproduce this issue by following these steps:
Using the instructions from: https://ylv.io/ethernaut-alien-codex-solution/
```
data = "0x1d3d4c0b00000000000000000000000000000000000000000000000000000000000000201000000000000000000000000000000000000000000000000000000000000000"
await sendTransaction({to: contract.address, data: data, from: player, gas: 900000});
```
```
await contract.revise('35707666377435648211887908874984608119992236509074197713628505308453184860938', '0x00000000000000000000000013ebd3443fa5575f0eb173e323d8419f7452cfb1', {from:player, gas: 900000});
```

Thanks so much for reporting it!

**Comment by ylv-io** [comment]
This is quite strange indeed, because solc shouldn't generate an array boundary check before [version 0.4.9](https://github.com/ethereum/solidity/releases/tag/v0.4.9), but I do get `Error Message: invalid opcode 0xfe` error on my transaction. Need more time to invistigate.

**Comment by ShehryarShoukat96** [comment]
Hi @ylv-io, I am getting the same error (`Error Message: invalid opcode 0xfe`) on Solc version 0.5.0. Do you have any idea about this?

**Comment by frangio** [comment]
Hi everyone, we can confirm that the level can be solved, but the solution guide shared above is a bit outdated.
