### ISSUE TITLE
Update web3 to 1.3.0+

### ISSUE THREAD

**Issue by MrClottom** [OpenZeppelin/ethernaut#179]
Please update the version of the web3 instance injected into the console. 

Not only is the 0.20 version outdated I can't seem to find documentation for it, making challenges especially challenging to solve.

**Comment by hensha256** [comment]
Hey @MrClottom! Today we updated Ethernaut to use 1.2.27. We are hoping to move to 1.3.0 as soon as possible, but it brought in a couple of changes that mean the code needs to be updated, so we will need a little time to make that update.
