### ISSUE TITLE
Availability of the game on other testnets?

### ISSUE THREAD

**Issue by juanpcapurro** [OpenZeppelin/ethernaut#181]
Currently Ropsten has a very low gas limit of `155040`, and yesterday there weren't any blocks for like an hour.

Additionally the community doesn't seem to be very active on it, and it's hard to find a faucet that works.

Is the game available on other testnets?

If not, IMO it would make sense to host another instance on Kovan or Rinkeby

**Comment by abcoathup** [comment]
Hi @juanpcapurro,

Thanks for reporting.  Ethernaut is only available on Ropsten currently.  
Ropsten has been problematic recently so we are looking at the best way to deal with this.

**Comment by hensha256** [comment]
Hey @juanpcapurro! Today we launched a Rinkeby version of Ethernaut. You can find it at ethernaut.openzeppelin.com. The Ropsten version will still be available at ropsten.ethernaut.openzeppelin.com
