### ISSUE TITLE
Transaction fails - authenticate function sets cleared to true

### ISSUE THREAD

**Issue by overqint** [OpenZeppelin/ethernaut#189]
Thanks for the great game and this level.

Level 0 Hello Ethernaut:

Don't know if this is intended or not?

Chrome console, after calling: 

`
await contract.authenticate('ethernaut0')
`
metamask starts a transaction

even if the transaction fails, cleared is set to true and the level is cleared.

#contracts/levels/Instance.sol

```
function authenticate(string memory passkey) public {
    if(keccak256(abi.encodePacked(passkey)) == keccak256(abi.encodePacked(password))) {
      cleared = true;
    }
  }
```

@ajsantander

**Comment by abcoathup** [comment]
Hi @overqint,

I tried to reproduce, Level 0 Hello Ethernaut

In the developer console I ran the following:
```
await contract.authenticate('ethernaut0')
```
I then Rejected the transaction in MetaMask

Checking the value of cleared returns false
```
await contract.getCleared()
false
```

Is there something that I am missing?

**Comment by overqint** [comment]
It behaves like you described, could not reproduce the issue again; closing it. 
Thanks for checking it out @abcoathup

**Comment by abcoathup** [comment]
Thanks for trying again @overqint.  I will close this issue as neither of us could reproduce.
