### ISSUE TITLE
ropsten.ethernaut.openzeppelin.com warns on wrong network and to switch to Rinkeby

### ISSUE THREAD

**Issue by abcoathup** [OpenZeppelin/ethernaut#191]
ropsten.ethernaut.openzeppelin.com warns that the user is on the wrong network and to switch to Rinkeby.

![image](https://user-images.githubusercontent.com/28278242/101295514-2601a000-3872-11eb-88d1-615b75f4e2d1.png)

Switching to Rinkeby and Ethernaut is playable.

**Comment by Glisch** [comment]
In the source js can see

` // export const ACTIVE_NETWORK = NETWORKS.ROPSTEN
var ACTIVE_NETWORK = exports.ACTIVE_NETWORK = NETWORKS.RINKEBY;
// export const ACTIVE_NETWORK = NETWORKS.LOCAL`

And doing `ACTIVE_NETWORK = exports.ACTIVE_NETWORK = NETWORKS.ROPSTEN;` in the console allows it to be used in the meantime.

**Comment by frangio** [comment]
This is fixed now. Apologies for the inconvenience!
