### ISSUE TITLE
Rinkeby faucet not working

### ISSUE THREAD

**Issue by clifton** [OpenZeppelin/ethernaut#194]
See: https://github.com/ethereum/go-ethereum/issues/21166

Hi, I can't finish chapter 0 of ethernaut as the faucet doesn't seem to be working, and it's not clear anyone is planning to fix it. Is there any guidance on how to proceed? Thanks

**Comment by mpetrone** [comment]
I had the same issue. I used https://ropsten.ethernaut.openzeppelin.com/ where the faucets are working fine.

**Comment by abcoathup** [comment]
Hi @clifton,

I am sorry that you had this issue with the faucet.  If you post a Rinkeby address I can transfer some Rinkeby Ether.

**Comment by abcoathup** [comment]
You can also try the MyCrypto faucet: https://app.mycrypto.com/faucet

**Comment by abcoathup** [comment]
Hi @clifton & @mpetrone,

The Rinkeby faucet is up and running again: https://twitter.com/peter_szilagyi/status/1346031644436815872?s=20

**Comment by mpetrone** [comment]
too late :) I have already finished all the levels on ropsten.

thanks for all the contribution to the community! It was really fun!

**Comment by abcoathup** [comment]
Hi @mpetrone,

>I have already finished all the levels on ropsten.

Great!  You could add your solutions to the list of community solutions: https://forum.openzeppelin.com/t/ethernaut-community-solutions/561

For another challenge, you could look at: https://www.damnvulnerabledefi.xyz/
Community solutions: https://forum.openzeppelin.com/t/community-solutions-to-damn-vulnerable-defi/4744
