### ISSUE TITLE
Incompatibility with MetaMask

### ISSUE THREAD

**Issue by fmaduakor** [OpenZeppelin/ethernaut#199]
Metamask has discontinued injecting window.web3.
Frontend (ropsten) does not work anymore with metamask.

edit:// Seems to work with MetaMask Legacy Web3. However, no new instance is shown after sending transaction

**Comment by abcoathup** [comment]
Hi @fmaduakor,

Thanks for raising.  As this is a duplicate of #198, I will close this and we can pick up the discussion there.
