### ISSUE TITLE
Upgrade web3.js to latest minor

### ISSUE THREAD

**Issue by GregTheGreek** [OpenZeppelin/ethernaut#200]
The currently used version of web3.js is not compatible with the latest release of Metamask. Consider bumping to web3@^1.3.3

**Comment by abcoathup** [comment]
Hi @GregTheGreek,
Thanks for the suggestion, it is really appreciated.
Please see: https://github.com/OpenZeppelin/ethernaut/issues/198#issuecomment-763732953

PR's are welcome.
