### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by frangio** [OpenZeppelin/ethernaut#206]
We want to build a leaderboard to rank users on some metrics of their performance on Ethernaut.

### Metrics

1. Number of levels solved
2. Time (measured in block numbers?) from deployed to submission of correct solution

These metrics should be combined together to form a score for the ranking, possibly a weighted sum of both of these numbers. Open to discussion.

### Implementation

This leaderboard should be display in a menu in the UI.

The data should be stored on the chain and the UI should read directly from there (or it may be necessary or useful to use something like The Graph).

It would be really nice if people could submit a name to be display in the leaderboard. This would be implemented with a button in the leaderboard that allows users to write their name and send a transaction to register it.

We would love if we could gather this data from the past. Note that Ethernaut used to be deployed on Ropsten, so we would need to look at the previous contract.

CC @xaler5

**Comment by immaxkent** [comment]
@frangio see [PR#568](https://github.com/OpenZeppelin/ethernaut/pull/568) for mock leader board implementation(s) reading from `Statistics.sol` proxy on-chain + a `fetchAndWriteAliases` script mock-up awaiting UI integration, as per @xaler5 's directive. give him a big hug from me next time you see him
