### ISSUE TITLE
Reduce ether requirement for King challenge

### ISSUE THREAD

**Issue by wchargin** [OpenZeppelin/ethernaut#207]
With the Rinkeby faucet policies around social media, acquiring testnet
ether can be inconvenient. The "King" challenge is hard-coded to require
1 ETH from participants, and during the challenge it's convenient to
have additional ETH on hand. It would be nice to tune these constants
down by a few orders of magnitude; the lesson works just as well if the
initial bid in the King contract is something like 0.001 ETH.

**Comment by abcoathup** [comment]
Hi @wchargin!  Thanks for the suggestion, it is really appreciated.

The project owner will review your suggestion as soon as they can. 

Please wait until we have discussed this idea before writing any code or submitting a Pull Request, so we can go through the design beforehand.  We don’t want you to waste your time!

**Comment by ImportNN** [comment]
I'm bumping this because there is no reason for this contract to ask for such a big amount of eth with the faucets problem that we are having.

**Comment by xaler5** [comment]
Closed by https://github.com/OpenZeppelin/ethernaut/pull/303

**Comment by wchargin** [comment]
Thank you, @xaler5! :D
