### ISSUE TITLE
TypeError: Cannot read property '_middleware' of undefined

### ISSUE THREAD

**Issue by spobwoode** [OpenZeppelin/ethernaut#227]
I'm getting this error on level 0 when using with Chrome + Metamask (on Rinkeby):

`main.c609416a.js:36880 Uncaught (in promise) TypeError: Cannot read property '_middleware' of undefined
    at Object.attachLogger (main.c609416a.js:36880)
    at _callee$ (main.c609416a.js:129011)
    at tryCatch (main.c609416a.js:128174)
    at Generator.invoke [as _invoke] (main.c609416a.js:128412)
    at Generator.prototype.<computed> [as next] (main.c609416a.js:128226)
    at step (main.c609416a.js:128951)
    at main.c609416a.js:128951`

![image](https://user-images.githubusercontent.com/8266893/125473363-8773187b-e48e-480a-902c-456e0ce545ee.png)

**Comment by cmade** [comment]
The solution for me was to remove any other additional wallet extension that is not MetaMask. For me I removed my Coinbase wallet extension and it got rid of the error.

**Comment by xaler5** [comment]
Hey @spobwoode have you tried @cmade suggestions ?

**Comment by xaler5** [comment]
@spobwoode can you try this version with an hotfix ?
https://613f77839a5b1800084a989d--openzeppelin-ethernaut.netlify.app/

**Comment by spobwoode** [comment]
Yep, it's working now, thanks. I also had to disable the Coinbase wallet extension I was using.

**Comment by xaler5** [comment]
Great, with this https://github.com/OpenZeppelin/ethernaut/pull/257 we should be able to catch MetaMask even if Coinbase wallet and Binance wallet extensions are installed.

Closing. Fell free to re-open if you still have the issue
