### ISSUE TITLE
King level broken? Passed it without any attempt of ethernaut reclaiming kingship

### ISSUE THREAD

**Issue by valer-cara** [OpenZeppelin/ethernaut#24]
I've sent an 1.01 Ether transaction to the King contract, then submitted the level and it passed.

I think it might be broken - expected the submission to fail due to:

> When you submit the instance back to the level, the level is going to reclaim kingship. You will beat the level if you can avoid such a self proclamation.

The 1.01 Eth tx: https://ropsten.etherscan.io/tx/0x7b1eda07bfcb6f2e0c02e6d79732a35dd7c39bd689dd371ba0f823b3f477d6d9

PS: great game! feels like a solidity & eth security crash course <3

**Comment by ajsantander** [comment]
I'm not able to reproduce this issue. The tests specifically check for the situation you describe and they currently pass... I also tested doing what you say with the dApp in ropsten and I wasn't able to complete the level in that way.
