### ISSUE TITLE
Cannot interact with contract... `Error in RPC response:,err: max fee per gas less than block base fee`

### ISSUE THREAD

**Issue by kylebakerio** [OpenZeppelin/ethernaut#286]
@ https://ethernaut.openzeppelin.com/level/0x4E73b858fD5D7A5fc1c3455061dE52a53F35d966

input:
> await ethernaut.owner()

output:

> MetaMask - RPC Error: err: max fee per gas less than block base fee: address 0xCA6b8EaB76F76B458b1c43c0C5f500b33f63F475, maxFeePerGas: 20000000 baseFee: 29766651531 (supplied gas 1010499) 
> be0fc955ecd3144351755cc846b52f82df0b3c0a.js:1 Error in RPC response:,err: max fee per gas less than block base fee: address <my public address>, maxFeePerGas: 20000000 baseFee: 18680531271 (supplied gas 2000000)

:/

**Comment by kylebakerio** [comment]
fwiw:

this was me following the opening instructions in order, to play with the ethernaut contract a bit before moving on. It didn't work, had to use the workaround above, but it turned out to be relatively irrelevant--I'd just change the instructions to prevent someone else falling down this rabbit hole--as the rest of the course worked fine.

**Comment by DragonDev1906** [comment]
You (should) only need one `call()`. The following works for me: `await ethernaut.contract.methods.owner().call()`.

I haven't looked far into the code, but I think this may be a result of EIP-1559 (London). I think `ethernaut`is a wrapper object that fails due to these changes, while `ethernaut.contract`is the truffle contract that this wrapper object uses, given that this is how you call methods in truffle.

**Comment by DarqueWarrior** [comment]
I appreciate you posting this because I ran into the same issue today.

**Comment by r0mille** [comment]
I ran into this today.

**Comment by JithinKS97** [comment]
Hey @kylebakerio, does giving gasPrice explicitly helping? Like `await ethernaut.owner({ gasPrice:0 })`?

**Comment by JithinKS97** [comment]
@r0mille Can you specify the network and the level in which you are facing this issue?

**Comment by JithinKS97** [comment]
I think specifying gas fee like this is helping `await ethernaut.owner({ gasPrice:0 })`

**Comment by xaler5** [comment]
This issue is acknowledged and already solved in this PR
https://github.com/OpenZeppelin/ethernaut/pull/422
, once merged it should work normally

**Comment by J-mastenbroek** [comment]
When is the merge happening? Running into the same issue

**Comment by xaler5** [comment]
Fixed here
https://github.com/OpenZeppelin/ethernaut/pull/429
