### ISSUE TITLE
Level 9 King cost too much ETH to deploy. Rinkeby faucet is often unavailable recently

### ISSUE THREAD

**Issue by wwbustb** [OpenZeppelin/ethernaut#292]
contract need to send test eth back someway

**Comment by wwbustb** [comment]
Level 10 Re-entrancy also need 1eth to deplay

**Comment by spiside** [comment]
@wwbustb I agree that the cost is too high at the moment. However, if you would like to get test ETH from a reliable faucet, I would recommend https://faucets.chain.link/rinkeby.

**Comment by xaler5** [comment]
Closed by https://github.com/OpenZeppelin/ethernaut/pull/303
