### ISSUE TITLE
Level 10: Re-entrancy - Compile Error for Solidity 0.6.0 through 0.6.1

### ISSUE THREAD

**Issue by Oighty** [OpenZeppelin/ethernaut#295]
Hello,

Ethernaut contracts are targeted at Solidity ^0.6.0, but Level 10 Re-entrancy does not compile when using 0.6.0 through 0.6.1 because of the `.call{value: amount}()` syntax in line 21.

The syntax for message calls with value was changed in Solidity 0.6.2 from` .call.value()() `to the provided `.call{value: }()`.
Links:
* 0.6.1: https://docs.soliditylang.org/en/v0.6.1/security-considerations.html?highlight=sending%20and%20receiving%20ether#sending-and-receiving-ether
* 0.6.2: https://docs.soliditylang.org/en/v0.6.2/security-considerations.html?highlight=sending%20and%20receiving%20ether#sending-and-receiving-ether

I'm not recommending it be changed back, but it may be good to update the Solidity version of the contract to ^0.6.2 to avoid the issue.

Thanks,

Oighty

**Comment by xaler5** [comment]
Changed to Solidity 0.6.12 :)
