### ISSUE TITLE
Calling the submit instance

### ISSUE THREAD

**Issue by ezeamaka2** [OpenZeppelin/ethernaut#301]
Trying to wrap my head around the game. Am able to interact with the smart contract from the console. But, I have been unable to move to the next game because I don't understand how to call the submit instance function

**Comment by xaler5** [comment]
Hello @ezeamaka2 , don't you find an orange button below saying `submit instance` ?

![image](https://user-images.githubusercontent.com/20795374/147685246-9b2bd08f-7395-4a2b-afb1-37ece20a5965.png)

**Comment by ezeamaka2** [comment]
I do, do I have to click on it or I have to call it from the console?

I have been trying to call the function from the console and its not working

**Comment by xaler5** [comment]
Yes you should click the button. I'm closing this but fell free to reopen if it still doesn't work
