### ISSUE TITLE
Level 24 PuzzleWallet contract creation error

### ISSUE THREAD

**Issue by merlincdj** [OpenZeppelin/ethernaut#306]
https://rinkeby.etherscan.io/tx/0x00fb62b0c37d8fed2c268ba60ce26d75fbe2ec39b5b7257341fcef425f84f594

**Comment by xaler5** [comment]
Thanks @merlincdj it should be fixed now with this
https://github.com/OpenZeppelin/ethernaut/commit/d897766309dc00e7a4d33361e17fa705a9093874

I'm closing this. Fell free to reopen if it still persists

**Comment by merlincdj** [comment]
Still error now, the only difference is without sending 1ether when creating the contract.
https://rinkeby.etherscan.io/tx/0x8aa0b5b00a2be11677e807d119a57311d23896aacd6d0ff6cf9f012e4940d2cd
