### ISSUE TITLE
Level 24 contract creation error

### ISSUE THREAD

**Issue by merlincdj** [OpenZeppelin/ethernaut#308]
Pre issue here #306 , but still error in contract creation. Btw, I can't re-open the old issue because closed by repo collaborator.
Error creation tx after #306 here:https://rinkeby.etherscan.io/tx/0x8aa0b5b00a2be11677e807d119a57311d23896aacd6d0ff6cf9f012e4940d2cd

**Comment by xaler5** [comment]
Great @merlincdj  sorry about it. Just sent an hotfix. Wait few minutes and let me know if it works now. I'll leave this open

**Comment by merlincdj** [comment]
Thanks @xaler5 It can work now.
