### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pudelkoM** [OpenZeppelin/ethernaut#31]
Under which license is ethernaut published? Is it the same as for zeppelin-solidity?

This is relevant if you'd like to run your own public version.

**Comment by roschler** [comment]
Bumping this thread since it's an important issue.

**Comment by Raz0r** [comment]
+1

**Comment by ajsantander** [comment]
Implementing GPL here: https://github.com/OpenZeppelin/ethernaut/pull/43
