### ISSUE TITLE
writing development deploy addresses to gamedata.json causes merge conflicts

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#32]
When a level is deployed during development, a level's "deployment_development" member is written to. "deployment_ropsten" is supposed to be unique but "deployment_development" is not, and is currently causing merge conflicts.

Consider extracting development deployment addresses to a separate file that can be gitignored.

**Comment by syncikin** [comment]
Another problem with the current behaviour is that when it ships it defaults to your `deployed_ropsten` address, so when someone else tries to deploy on ropsten by calling `registerLevel()` they won't be the owner of the contract and the tx will fail (spent a couple hours figuring out why nothing was working on ropsten!). 

Having a separate gitignored file that defaults to `x` and forces a fresh deployment of everything should fix this issue as well.

**Comment by ajsantander** [comment]
Yup, my plan is to separate deployment addresses from the gamedata file and have deployment files for each network. The development network can be gitignored. I'll take this one!
