### ISSUE TITLE
Level 25 Motorbike instance validation is faulty

### ISSUE THREAD

**Issue by evonide** [OpenZeppelin/ethernaut#329]
Steps to reproduce:
1) Create a new Motorbike instance at https://ethernaut.openzeppelin.com/level/0x78e23A3881e385465F19c1a03E2F9fFEBdAD6045
2) Wait until [someone else has also created an instance](https://rinkeby.etherscan.io/address/0x78e23a3881e385465f19c1a03e2f9ffebdad6045#internaltx). This happens every few hours.
3) Solve the level correctly and submit the instance.

Expected behavior:
- Level is completed and win message gets displayed.

Actual behavior:
- "Oops! Looks like you haven't cracked this level just yet" is displayed and the level gets bricked.
------------
Analysis:
https://github.com/OpenZeppelin/ethernaut/blob/master/contracts/contracts/levels/MotorbikeFactory.sol
Uses the following code:
```
contract MotorbikeFactory is Level {
  Engine public engine;
  Motorbike public motorbike;
function createInstance(address _player) public payable override returns (address) {[...]}
[...]
  function validateInstance(address payable _instance, address _player) public override returns (bool) {
    _player;
    _instance;
    return !Address.isContract(address(engine));
  }
}
```
`validateInstance` does NOT utilize the passed `_instance` variable.

Instead, it always uses the engine storage variable. When someone requests a new instance of the Motorbike level `createInstance` gets called which in turn will overwrite `engine` making it impossible to win this level with the initially given instance.

**Note:** Someone can win this level by submitting their unsolved instance if the current `engine` instance is in a solved state.

Suggested fix:
- `validateInstance` needs to instead retrieve the Engine contract address for the given `_instance` variable. Since this one is stored at `0x360894a13ba1a3210667c828492db98dca3e2076cc3735a920a3ca505d382bbc` of the passed Motorbike `_instance` this might be tricky to retrieve though.

**Comment by xaler5** [comment]
Thanks @evonide we have already a fix on the way !

I'll post here the commit once merged

**Comment by xaler5** [comment]
@evonide Fix has been pushed to master https://github.com/OpenZeppelin/ethernaut/commit/d641313e4b284fa5272bf644c8b3c9a3326c4695

You can see how the new `MotorbikeFactory` works 
https://github.com/OpenZeppelin/ethernaut/blob/master/contracts/contracts/levels/MotorbikeFactory.sol

Let me know if you still have the issue. I'm closing this for the moment. Fell free to re open it
