### ISSUE TITLE
Level 13 of ethernauts is not verified on etherscan, making it harder than intended

### ISSUE THREAD

**Issue by kylebakerio** [OpenZeppelin/ethernaut#331]
[official solution](https://medium.com/coinmonks/ethernaut-lvl-13-gatekeeper-1-walkthrough-how-to-calculate-smart-contract-gas-consumption-and-eb4b042d3009) shows a verified contract, which can be emulated on remix in a straightforward fashion, which is relatively necessary to predict gas costs during operation.

I was not quite able to verify, but almost. Getting OZ's safemath 0.6.0, and pasting it in place of the import statement, got identical bytecode except for this part dangling at the end I wasn't able to account for yet:

`a26469706673582212202d807b96389b246b6031859c4c828eb95e688157a516ac849532642a70ebfd3d64736f6c63430006030033`

Anyways, that should still be close enough to estimate gas costs, but it does add some indirection that may not (?) be desired. I do find it odd that this is a 5/10 and privacy is an 8/10--privacy felt easy, solving the gas calculations felt trickier to me, but I dunno. Maybe storage is just something I was personally more familiar with.

**Comment by kylebakerio** [comment]
My path to solving it literally involved me sitting down and converting the on-chain bytecode to opcodes and manually calculating gas usage of each executed bytecode up through the `GAS` call and tracing the path of call manually, guided by watching remix debug follow the opcodes of the similar (but not identical) bytecode from my local-compiled-near-clone of the guessed solidity. This worked fairly well and was not _quite_ as bad as it sounds, but I think decompiling bytecode and working with raw opcodes is... not an insubstantial bar.

Alternative is to brute force the difference, which is the only existing solution I've seen out there after checking.

Not sure if the update to 0.6.0 was intended to raise the bar a bit or not, anyways. If so, feel free to close this, but I'd suggest raising the difficulty rating above 5/10 to something closer to the `privacy` one, at least.

**Comment by xaler5** [comment]
Hello @kylebakerio have you considered using this repo ? You can clone it and compile contracts in local with same settings as they are deployed in Rinkeby. In this way you might have anything you need. 

In any case you are right that contract was verified in the past and now it is not anymore. We will consider either adjusting difficulty or adding a verification.

**Comment by kylebakerio** [comment]
> have you considered using this repo ?

did you forget to add a link? Not sure what repo you're referring to.

> In any case you are right that contract was verified in the past and now it is not anymore. We will consider either adjusting difficulty or adding a verification.

sounds good! I kind of like it the way it is unverified, but does raise the bar.

**Comment by xaler5** [comment]
> did you forget to add a link? Not sure what repo you're referring to.

I meant this repo where are we discussing. The ethernaut one
https://github.com/OpenZeppelin/ethernaut

**Comment by mtomassoli** [comment]
Here's how I solved it.
First I deployed a modified version of GatekeeperOne.sol:

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.6.0;

import "@openzeppelin/contracts/math/SafeMath.sol";

contract MOD_GatekeeperOne {
    using SafeMath for uint256;
    address public entrant;
    uint public gasLeft;

    modifier gateOne() {
        require(msg.sender != tx.origin);
        _;
    }

    modifier gateTwo() {
        uint gl = gasleft();
        // require(gasleft().mod(8191) == 0);
        gasLeft = gl;
        _;
    }

    function enter(bytes8 /*_gateKey*/)
        public
        gateOne
        gateTwo
        // gateThree(_gateKey)
        returns (bool)
    {
        entrant = tx.origin;
        return true;
    }
}
```
I found a best guess using that modified version and then attacked the original version by brute forcing around that guess (0, -1, +1, -2, +2, ...): 50 attempts were enough. I wrote a JS script, of course.

**Comment by kylebakerio** [comment]
I compiled my own version, which resulted in very similar but not identical bytecode. I then tracked the gas usage for each command along the stack and measured it myself.

Fun, but felt a little crazy.

Brute forcing is the more typical answer.

**Comment by xaler5** [comment]
The game now should verify the contract after creation, let me know if it works well on your side :)
