### ISSUE TITLE
Deploy Ethernaut to Goerli or Sepolia

### ISSUE THREAD

**Issue by rootulp** [OpenZeppelin/ethernaut#340]
### Description
It seems like Rinkeby will be deprecated. Are there plans to deploy Ethernaut to Goerli or Sepolia?

### Motivation
> Keep shadow forking until no client issues, then upgrade Ropsten, followed by shorter timeframe for Goerli & Sepolia
> Rinkeby won’t be upgraded; Ropsten & Rinkeby will be deprecated

[Source](https://weekinethereum.substack.com/p/week-in-ethereum-news-april-16-2022?token=eyJ1c2VyX2lkIjo5MjIwNTQxLCJwb3N0X2lkIjo1MjMwNTExMywiXyI6IjZSY1pRIiwiaWF0IjoxNjUwMTMwODYxLCJleHAiOjE2NTAxMzQ0NjEsImlzcyI6InB1Yi0xMDcxIiwic3ViIjoicG9zdC1yZWFjdGlvbiJ9.sbvFqgdWVd6ya1y7YU9J51h_jJNOIgkV5qPym6KNbH8&s=r)

**Comment by elizabethdinella** [comment]
Is there any update on this?

**Comment by robercano** [comment]
Bumping this up. Currently Infura and Alchemy have already deprecated their API for Rinkeby.

**Comment by scvsh** [comment]
Infura RPC stopped Rinkeby support — no way to interact with the app anymore. 
`Network decommissioned, please use Goerli or Sepolia instead"`

**Comment by damoklov** [comment]
Confirming that Ethernaut cannot connect to Metamask via Rinkeby due to 'outdated RPC'.
![image](https://user-images.githubusercontent.com/37833994/194161717-ae099bfd-b316-4f7d-91e0-159cdd8229e7.png)

**Comment by sseefried** [comment]
Given that the website for Ethernaut just received a facelift -- it looks great by the way! -- it seems like OZ really wants people to play Ethernaut. Hence addressing this issue is going to be pretty important.

**Comment by xaler5** [comment]
Hello everyone. The issue is now solved please refer to this

https://github.com/OpenZeppelin/ethernaut/issues/402#issuecomment-1271230606

**Comment by 0xolishell** [comment]
[March 2023 update] Goerli and Sepolia are the two Ethereum testnets to use. Goerli is more popular but is experiencing some congestion / cost issues currently.  If you're trying to decide which one to use, [here's an article that explains the difference between the two](https://www.alchemy.com/overviews/goerli-vs-sepolia). 

If needed, here are Alchemy's free faucets for each. You can get more testETH every day

- [Goerli Faucet](https://goerlifaucet.com)
- [Sepolia Faucet](https://sepoliafaucet.com)
