### ISSUE TITLE
Error in progress

### ISSUE THREAD

**Issue by shlok2740** [OpenZeppelin/ethernaut#364]
There is an error in the progress system of Ethernaut. I have done 6 levels but the progress isn't showing.

![lv6](https://user-images.githubusercontent.com/77238805/174013208-49429e85-d2b9-4cb0-b250-9df7d56a37c7.PNG)
![lv7](https://user-images.githubusercontent.com/77238805/174013219-88991e61-9f69-47ea-9b82-7b513e47d778.PNG)

**Comment by immaxkent** [comment]
hi @shlok2740 can you tell me if you have rejected cookies/are browsing in an incognito/private browser setting?

**Comment by shlok2740** [comment]
No, I don't think that I have used incognito mode

**Comment by xaler5** [comment]
@shlok2740 we have moved everything to Goerli now and progresses are saved on chain so they are not lost. I'm closing this issue right now, if you still face the same problem moving forward fell free to re-open it
