### ISSUE TITLE
[Level 24 - Puzzle Wallet] - Not clear and source code not available

### ISSUE THREAD

**Issue by Azephiar** [OpenZeppelin/ethernaut#389]
Hi, I was trying to solve level 24 and found 2 issues.

1) The dependency "@openzeppelin/contracts/proxy/UpgradeableProxy.sol" is no longer available or either it's not clear where to find the code. This means I had to solve the puzzle based on assumptions on how that dependency managed storage.

2) The stated rules are to "become admin of the proxy contract" but I think the actual requirements includes draining the funds as well.

**Comment by mtomassoli** [comment]
1. I'm using @openzeppelin/contracts@3.4.2 without any problems.
2. The requirement is just to become the admin. All the other things one needs to do to become the admin shouldn't be stated as additional requirements as they're for the player to figure out.

**Comment by xaler5** [comment]
Thanks for the solution @mtomassoli , I'm closing this, fell free to reopen if necessary into Github discussions
