### ISSUE TITLE
Completed levels cleared

### ISSUE THREAD

**Issue by OmiAkk** [OpenZeppelin/ethernaut#397]
Hi! I cleared my browser cookie files and all my completed levels disappeared... Is there a way to fix this? Thanks for the awesome game!

Edit: spelling

**Comment by xaler5** [comment]
Progresses are now stored on chain moving forward. I'm closing this issue since we already merged the necessary changes. Let me know if you still face the same issue !

**Comment by OmiAkk** [comment]
That's awesome! Thank you! I'm contributing to the Ethernaut with russian translations now! Sent a PR already :)
