### ISSUE TITLE
Unable to "Get new instance" following Rinkby deprecation 

### ISSUE THREAD

**Issue by johnsonstephan** [OpenZeppelin/ethernaut#404]
**Issue Description** 

Error message received following clicking on "Get new instance"

> Ethernaut contract not found in the current network. Please make sure (1) that you are using metamask, (2) that it's on the rinkeby testnet, (3) that it is unlocked, (4 optional) From November 2 you can turn ON privacy mode (OFF by default) in Metamask settings if you don't want to expose your info by default. (5 optional) If privacy mode is turn ON you have to authorized metamask to use this page. and (6) then refresh.

**How to reproduce**

1. Select Rinkby test network in wallet
2. Navigate to a level
3. Click on "Get new instance"

**Screenshot**

![image](https://user-images.githubusercontent.com/16626913/194172482-7bedf9c4-f7ee-4bd6-98b3-dc34e76fec84.png)

**Note(s)**

- _Last working:_ I was able to create a new instance 8 hours ago. It seems the Rinkby deprecation is causing the issue 
- _Related issue:_ unable to interact with the ABI. Calling "ethernaut" results in an error: Uncaught ReferenceError: ethernaut is not defined at <anonymous>:1:1

**Comment by Matlemad** [comment]
Just adding my written support for this issue: Ethernaut is such a finely designed educational tool, it would be a real pity to see its community abandoning it and taking on other courses just because it stays unavailable for a long period of time.

**Comment by xaler5** [comment]
The issue should be solved. We just made it available in different testnets:
Sepolia, Goerli and Mumbai. Ropsten and Rinkeby are still there but they will get removed soon. Try it out!

**Comment by johnsonstephan** [comment]
We are back in business! @xaler5, thank you sir for the quick fix!

![image](https://user-images.githubusercontent.com/16626913/194410841-3c0a3e84-b63c-4a41-8d9d-7dcc7817771f.png)

**Comment by Matlemad** [comment]
Goerli is not working (and Sepolia Faucets are empty), same message appears:

f4a50c016452ba93cd8137d29eb24fae516b0d42.js:1 \˚ㄥ˚\ Ethernaut contract not found in the current network. Please make sure (1) that you are using metamask, (2) that it's on a supported network, (3) that it is unlocked, (4 optional) From November 2 you can turn ON privacy mode (OFF by default) in Metamask settings if you don't want to expose your info by default. (5 optional) If privacy mode is turn ON you have to authorized metamask to use this page. and (6) then refresh.

**Comment by xaler5** [comment]
@Matlemad have you cleared your cache and made sure your correctly connected with metamask? I'm running fine in Goerli
