### ISSUE TITLE
❌ Ethernaut contract not found in the current network

### ISSUE THREAD

**Issue by PedroReyes** [OpenZeppelin/ethernaut#407]
Hello,

*️⃣ Context
I am doing for the Spanish community a series of Ethernaut games explanation but right now the website is not creating properly the instances of the contract levels. 

🔴 https://www.youtube.com/c/PedroReyesDev

*️⃣ Error

The error provided by the website is: `Ethernaut contract not found in the current network`. See image attached.

![image](https://user-images.githubusercontent.com/4096108/194921769-e055fbe6-03a4-466f-ad43-8ef3b09bfbfd.png)

*️⃣ Steps I already took

1. Refresh the website
2. Clear site data and doing a hard reload 
3. Switching networks in both places Metamask and the network dropdown button available at the website

Best regards,
Pedro Reyes.

**Comment by PedroReyes** [comment]
Hello,

In the Goerli testnet the contract of NaughtCoin seems to be deployed correctly. Therefore, if there is no solution to the general issue in the other networks I recommend switching to Goerli testnet.

Best regards,
Pedro Reyes.

**Comment by xaler5** [comment]
@PedroReyes that is a level deployed on Rinkeby. Following The Merge, Rinkeby and Ropsten are deprecated and Goerli or Sepolia are the official testnets now, please be sure to use one of those or Mumbai as alternative, we are slowly deprecating Rinkeby and Ropsten and those will be soon removed from the game. 

I'm closing this issue but fell free to reopen it if something goes wrong.
