### ISSUE TITLE
404 Not Found error when selecting a level

### ISSUE THREAD

**Issue by davidkathoh** [OpenZeppelin/ethernaut#413]
Ethernaut is currently returning  a 404 page when a level is clicked

**Comment by xaler5** [comment]
Hello @davidkathoh  ! Can you give some more context ?

Which browser are you using ? Is metamask correctly connected ? If yes, to which chain ? Can you provide a screen ?

I currently can't reproduce the issue. 

As first thing, did you try deleting cache ?

**Comment by davidkathoh** [comment]
I have tried to reinstall Metamask, it's now working
