### ISSUE TITLE
Can't find the help link

### ISSUE THREAD

**Issue by Josephdara** [OpenZeppelin/ethernaut#558]
https://github.com/OpenZeppelin/ethernaut/blob/master/client/src/gamedata/en/descriptions/levels/coinflip.md)
There's no link at Beyond the console

**Comment by xaler5** [comment]
Fixed in here
https://github.com/OpenZeppelin/ethernaut/pull/612

You need to click on the "?" icon in the dropdown menu. Thanks for pointing it out
