### ISSUE TITLE
Adjusting Difficulty level for Privacy & Gatekeeper One

### ISSUE THREAD

**Issue by 14si2o** [OpenZeppelin/ethernaut#579]
Hello, 

Currently the Privacy level has a difficulty level of 4/5. I do not believe this is warranted since since it is immediately clear (especially after completing the Vault level) that the challenge resolves about storage layout and using web3.eth.getStorageAt(). 

Therefore I would suggest a difficulty level of at most 3/5.

***

The Gatekeeper One level has a difficulty level of 3/5 but the difficultly gap between this and the previous levels is exceptionally high. Not only is it required to know/study the exact gas opcodes in order to calculate the gas to be used, but a proper understanding of bitmasking is required to understand how to pass the third gate. 

From what I searched on the web, it is also widely known as very complicated for a beginner (f.e. D-Squared Ethernaut series on youtube).

There I would suggest a difficulty level of 4/5.

**Comment by GianfrancoBazzani** [comment]
Thanks for the suggestions!

**Comment by 14si2o** [comment]
It's a pleasure to be able to contribute!
