### ISSUE TITLE
Add GateKeeper level tests after theCyber publishes solutions

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#58]
See comment in code:
https://github.com/OpenZeppelin/ethernaut/blob/master/test/levels/Gatekeeper.test.js#L27

**Comment by 0age** [comment]
Thanks for letting the tests slide for now @ajsantander 😁 

I'll fill in the tests (and add attack contracts) once the gatekeeper contract on the mainnet has taken 128 entrants (there are 58 as of now). You can read the contract at [gatekeepertwo.thecyber.eth](https://etherscan.io/address/gatekeepertwo.thecyber.eth#readContract) (the pertinent field is `totalEntrants`).
