### ISSUE TITLE
Change Testnet Recommendation to Sepolia

### ISSUE THREAD

**Issue by emnul** [OpenZeppelin/ethernaut#642]
Goerli gas prices have become very volatile since the merge going as high as 0.3 ETH to interact with ethernaut. This makes the dApp very unreliable on Goerli and provides a poor experience for newcomers entering the space. We should change the recommended network to Sepolia to improve the ethernaut UX.

<img width="343" alt="Screenshot 2023-04-19 at 23 01 28" src="https://user-images.githubusercontent.com/34749913/233209929-6ee0752f-17e4-4b5f-a9a6-2224c50e0953.png">
<img width="330" alt="Screenshot 2023-04-19 at 23 03 39" src="https://user-images.githubusercontent.com/34749913/233209955-43a18a77-cbdb-4ca4-a798-03a31c330413.png">

**Comment by GianfrancoBazzani** [comment]
We will do that ASAP, thanks for the advice!
