### ISSUE TITLE
Cannot create new instance for level 19 Alien Codex in Sepolia testnet: execution reverted: Level doesn't exist

### ISSUE THREAD

**Issue by 14mbda** [OpenZeppelin/ethernaut#651]
# Issue
The tx to call `createLevelInstance` for level 19 Alien Codex(Level contract `0x27bC920e7C426500a0e7D63Bb037800A7288abC1`) in Sepolia testnet revert with error `Level doesn't exist`. Example tx: https://sepolia.etherscan.io/tx/0x8893b52bd83bd3c393508cb4973e207d7c4bad582cb1d7502a3c22e4f10da357
<img width="632" alt="image" src="https://user-images.githubusercontent.com/132259657/235457793-d4058a84-da2f-4f18-8fbc-785a25add666.png">

# Steps to reproduce
1. Use Sepolia testnet in wallet
2. Go to ethernaut page for level 19 Alien Codex
3. Click "Get new instance" 
4. Approve tx
5. Check error in console

**Comment by 14mbda** [comment]
I am getting the same issue with `goerli-optimism`.

**Comment by GianfrancoBazzani** [comment]
Hey guys, sorry for the inconvenience, the game is under maintenance, it will be live again as soon as possible.

**Comment by GianfrancoBazzani** [comment]
Hey Ethernauts it should be fixed now, the game is live again! I proceed to close this issue
