### ISSUE TITLE
Challenge not working

### ISSUE THREAD

**Issue by sre3ed** [OpenZeppelin/ethernaut#671]
I was doing ethernaut coin flip challenge, so I did coding on remix and also connected my metamask account to it. Even though I cracked the challenge that is to flip coin for 10 times then when I clicked ethernaut website to submit button to submit, it is showing I didn't cracked the challenge
How to fix this problem?

**Comment by cy4n1d3-p1x3l** [comment]
please provide additional info 
like the remix code for example

**Comment by DanielBoye** [comment]
@sre3ed Please provide additional info or we can close this issue.

**Comment by marcobesier** [comment]
I recently completed the level, and everything worked just fine. I think you can close this issue.

**Comment by GianfrancoBazzani** [comment]
thanks for the feedback @marcobesier , I proceed to close this issue
