### ISSUE TITLE
Ethernaut contract not found in any network

### ISSUE THREAD

**Issue by sebastiantf** [OpenZeppelin/ethernaut#689]
getting the error on any network: goerli, sepolia, mumbai etc.

<img width="1234" alt="Screenshot 2023-11-06 at 1 43 53 PM" src="https://github.com/OpenZeppelin/ethernaut/assets/36922376/9534b385-f555-4036-9423-3f3ae3baa4c2">

**Comment by cy4n1d3-p1x3l** [comment]
Can you please confirm whether you have the following requirements:
1) metamask installed and functioning
2) sepolia testnet eth from a faucet enough to make some transactions

**Comment by sebastiantf** [comment]
It seems to be working after a few refreshes on goerli and sepolia. Didnt work on mumbai still

**Comment by GAlcaraz** [comment]
Getting the same issue as of the end of last week. Found across different browsers. Any insight into solving it, or what could have caused it?

**Comment by bebofit** [comment]
I tried goerli, sepolia and mumbai and getting same issue? did anyone find an answer?

**Comment by payala** [comment]
Same thing here, no way to find deployed contracts. Metamask version 11.4.1 on Chrome.

**Comment by wallebach** [comment]
Doesn't work for me neither. Firefox/Chrome and Metamask 11.4.
