### ISSUE TITLE
Leaderboard not fetching results properly (Sepolia)

### ISSUE THREAD

**Issue by jdetychey** [OpenZeppelin/ethernaut#710]
Hi folks,
It seems like the leaderboard is failing to pick up some contributions.
Please see the following addresses for example:
- [https://sepolia.etherscan.io/address/0x77ab9d6943523d7be464b0049c0424f8136c751a](https://sepolia.etherscan.io/address/0x77ab9d6943523d7be464b0049c0424f8136c751a
)
- [https://sepolia.etherscan.io/address/0x547de666743997C1Ce7E527dBb29dCC935a7B6D0
](https://sepolia.etherscan.io/address/0x547de666743997C1Ce7E527dBb29dCC935a7B6D0
)
- [https://sepolia.etherscan.io/address/0xd1aB3F375AEA3299cfA07b0B94A06A8a4eb7Bf84
](https://sepolia.etherscan.io/address/0xd1aB3F375AEA3299cfA07b0B94A06A8a4eb7Bf84
)
- [https://sepolia.etherscan.io/address/0xffc183aeea99987a9e0bee6e66583c88deb722a3
](https://sepolia.etherscan.io/address/0xffc183aeea99987a9e0bee6e66583c88deb722a3
)
- [https://sepolia.etherscan.io/address/0x68611254440d6ea902061fd78a1ffa3036372883
](https://sepolia.etherscan.io/address/0x68611254440d6ea902061fd78a1ffa3036372883
)
- [https://sepolia.etherscan.io/address/0x78316ACfb1d974AFf4E4B7B4e88F0c1F9C80D310
](https://sepolia.etherscan.io/address/0x78316ACfb1d974AFf4E4B7B4e88F0c1F9C80D310
)  

When looking for one of those addresses on the leaderboard page [https://ethernaut.openzeppelin.com/leaderboard](https://ethernaut.openzeppelin.com/leaderboard) (while connected to Sepolia), the leaderboard doesn't show any record for those addresses.

**Comment by renbou** [comment]
Seems like the leaderboard update script simply doesn't work anymore: https://github.com/OpenZeppelin/ethernaut-leaderboard/actions

**Comment by jdetychey** [comment]
For the context, I gave a solidity course to ~50 students and got them to ethernaut. This is may have spammed the script.

**Comment by renbou** [comment]
Seems more like the problem is due to Goerli deprecation - I've created a PR with a fix, waiting for the maintainers: https://github.com/OpenZeppelin/ethernaut-leaderboard/pull/18

**Comment by GianfrancoBazzani** [comment]
This Issue should be solved
