### ISSUE TITLE
bug: Link to an non existent Github account. 

### ISSUE THREAD

**Issue by SantiagoPittella** [OpenZeppelin/ethernaut#715]
The levels authored by @theethernaut (I think that this is his/her new nickname) have a broken link to the Github account.

Probably needs a change in the [L11 in the `authors.json`](https://github.com/OpenZeppelin/ethernaut/blob/master/client/src/gamedata/authors.json#L11)

**Comment by GianfrancoBazzani** [comment]
Thank @SantiagoPittella for reporting this, changes have been introduced here: https://github.com/OpenZeppelin/ethernaut/pull/700/commits/6ec3c51da648436e006bc9f3f9f72582e67b8a57
