### ISSUE TITLE
High score board

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#73]
If players were able to associate their address with an alias, we would be able to use the information to present some sort of high score page. The page would present some sort of high score board.

Something that could be useful is the Stats.js page, that is currently not being shown on the top menu bar, but is still reachable at: https://ethernaut.zeppelin.solutions/stats

This page collects on chain information about which levels have been completed by a player, or which players have completed a level. The highscore board could reuse some of this code and imitate the architecture, since it would be another Reactjs component.

It would be interesting to be able to associate a player to an alias via the cli, so that the page shows the alias when available and not just an obscure Ethereum address.

Also, regarding score, we could come up with some mechanism to count score. Perhaps considering level difficulty as a multiplier, or even counting the time that the player took to solve the level (resolution block - level instance creation block).

**Comment by TravisGDev** [comment]
Here is the design document for this task. This is a work in progress and I will update it with feedback and with any issues I face when coding the solution. This will ensure that none of the requirements are missed, the solution is efficient, potential bugs / attacks are taken care of and planned for, and that the solution fits within the vision of the Ethernaut team. All feedback / discussion is welcomed, big or small.

### 1. Player Alias
- (inspired by fomo3d). A new contract called Player will be created. Rough psuedo code below.

mapping (address => bytes32) public player_; 
- mapping of player alias by address

mapping (bytes32  =>  address) public alias_; 
- mapping of address by alias. To ensure duplicate alias do not exist and provide another way to look up who owns the alias

event setAlias (address indexed playerAddress, bytes32 indexed playerAlias)
- emit event when alias is added / changed

function aliasFilter(string _alias) internal pure returns(bytes32)
- filter alias
- converts uppercase to lower case.  
- makes sure it does not start/end with a space
- makes sure it does not contain multiple spaces in a row
- cannot be only numbers
- cannot start with 0x 
- restricts characters to A-Z, a-z, 0-9, and space.
@return reprocessed string in bytes32 format

function setAlias(string _alias) public 
- set the alias for the player if the alias is not in use, both mappings need to be updated

function isValidAlias(string _alias) public view returns(bool)
- a method to check if the alias already exists, do this in js before submitting the alias
- also use it when adding a name if the user bypasses the ui

**Optional:** Something to discuss. A way to remove or override alias which are deemed unacceptable. Only the owner of the contract can do this. This mapping could be populated during deployment. 

function setAliasAdmin(string _alias, address _player) public onlyOwner
- set the alias_ mapping to owner (blocking the alias), set the _player to empty

A js file will be created to handle interacting with the player contract so the user can set their alias using the cli. Tests will be created to ensure the functionality is bulletproof.

**Pros:**
- this contract containing player alias can be used across any Zeppelin apps.
- can migrate and upgrade player contract in the future if new fields or functionality is required without affecting the rest of the dApp.

**Cons:**
- users can use alias that may offend others.

### 2. High Score
- use gamedata.json difficulty as a multiplier. difficulty x 100.
- reuse Stats.js to build data set from on chain information.
- stats will be sorted by highest score, lowest block completed, lowest first block completed, alphabetical

I think using a timed rating on each level could cause potential problems. Users could create a js file to automate everything, giving them extremely short completion times. I think by using the filters above we can achieve a fair ranking.

**sorting explained with examples:**
name, level, block completed, difficulty

- ajsantander, fallback, 5, 1 
- ajsantander, fallout, 10, 2
- ajsantander, coinflip, 15, 3 
- ajsantander, fallout, 17, 2
**ajsantander score: 600.**


- travisgdev, fallback, 6, 1
- travisgdev, coinflip, 10, 3
- travisgdev, fallout, 16, 2
- travisgdev, fallout, 17, 2
**travisgdev score: 600.**


- noname, fallback, 17, 1
**noname score: 100.**

**1. Score:** Whoever has the highest score appears at the top. They have finished the most / toughest levels.

- 1st: ajsantander, travisgdev - 600.
- 2nd: noname - 100.

**2. Lowest Block Completed:** If a tie in #1, tiebreaker goes to the first user to get to the score. Only look at the block number of the first instance:
- ajsantander hit 600 points on coinflip at block 15. 
- travisgdev hit 600 points on fallout at block 16.
- ajsantander wins the tie breaker. He got to 600 first.

- 1st: ajsantander
- 2nd: travisgdev

**3. Lowest First Block Completed:** If a tie in #2, tie breaker goes to the user who started Ethernaut first (bonus for long time users). (first submission regardless of level)
- ajsantander, fallback, 5, 1 
- travisgdev, fallback, 6, 1
- ajsantander first completion at block 5. 
- travisgdev first completion at block 6.
- ajsantander wins the tie breaker.

- 1st: ajsantander
- 2nd: travisgdev

**4. Alphabetical:** In the unlikely event that a tie exists in #3, sort by alphabetical
- 1st: ajsantander
- 2nd: travisgdev

**Pros:**
- high scores are not stored, are built on the fly so they can be dynamic. The rules can be updated in js without needing to touch the smart contracts.

**Cons:**
- worried about efficiency and speed when building this potentially large dataset of on chain data. Will require testing this functionality with a large amount of dummy data.

Please leave any feedback. All of it is welcome.
