### ISSUE TITLE
Level 25 `MotorBike` level is unsolvable due to Dencun hardfork upgrade

### ISSUE THREAD

**Issue by fornitechibi** [OpenZeppelin/ethernaut#735]
## Description
Due to dencun update the `selfdestruct` is depreciated thus the contract now is not deleted unless if it's called within the same transaction as the contract's creation. Thus making the level unsolvable now.

**Comment by GianfrancoBazzani** [comment]
Hi @fornitechibi, there is a conversation regarding that topic in this issue https://github.com/OpenZeppelin/ethernaut/issues/701 , the level stills being solvable btw.
