### ISSUE TITLE
Cancun Upgrade Messes Up the assertion for MotorBike

### ISSUE THREAD

**Issue by Josephdara** [OpenZeppelin/ethernaut#737]
**The behavioural change specified here: https://docs.soliditylang.org/en/latest/units-and-global-variables.html#contract-related 
Directly impacts the assertion in the Motorbike Level.**

I came across issue when solving the Ethernaut challenges today. 
- After selfdestructing my `Engine` contract here: https://sepolia.etherscan.io/address/0x7c3fca81ae8f49d54c809064fd5f59fe201e8501
- The task itself is finalized, but the level does not pass. I believe this is due the fact that `From EVM >= Cancun onwards, selfdestruct will only send all Ether in the account to the given recipient and not destroy the contract`

A solution might be to change the assertion is the contract code remains after selfdestruct or remove the level completely

**Comment by GianfrancoBazzani** [comment]
Hey @Josephdara we already discussed that issue  here, i will close this one:

* https://github.com/OpenZeppelin/ethernaut/issues/701
