### ISSUE TITLE
[minor fix] Clearer instructions for lvl 19 

### ISSUE THREAD

**Issue by nczhu** [OpenZeppelin/ethernaut#78]
Hey @ajsantander ,

Loved this level, but was tripped up for ~1 hour by the instructions to "return 42".

I thought you wanted us to return the uint 42 (0x2a), i.e. answer to universe, life, everything. 
And was only able to pass after guessing you were checking for 0x42  😂

Possible to make instructions clearer? Thanks again~

**Comment by ajsantander** [comment]
Hmm. I see!
Ok, will check it out.

**Comment by ajsantander** [comment]
Good catch @nczhu ! (and stupid mistake from my side). 
Thx for reporting the bug. Would you do me a favor and peer review the fix? PR => https://github.com/OpenZeppelin/ethernaut/pull/82

**Comment by nczhu** [comment]
Looks like it's already merged! Thanks for considering & fixing :)

**Comment by ajsantander** [comment]
Awesome, thx!
