### ISSUE TITLE
Update to latest OpenZeppelin version

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#81]
Current dependency is fixed at 1.6.0 because later versions of OpenZeppelin introduce breaking changes for levels that were deployed using older versions. Levels must be upgradeable before this change is made.

See #94

**Comment by frangio** [comment]
Why do the levels have to be upgradeable?

**Comment by frangio** [comment]
When this issue was opened the dependency was at 1.6.0, but now Ethernaut is using OpenZeppelin Contracts 3.x. While it is not the most recent, it's recent enough for now!
