### ISSUE TITLE
Update Ethernaut to use ZeppelinOS

### ISSUE THREAD

**Issue by ajsantander** [OpenZeppelin/ethernaut#94]
Three strong reasons to do this:

(1) Right now, if a bug is discovered in a level, the code needs to be fixed and the level re-deployed. 

Ethernaut remembers which levels a player has passed, so this would mean that all history for a level is lost when it is re-deployed.

(2) Also, as Solidity matures, the levels will contain old code. It'd be nice to be able to update pragma versions on a level without losing history.

(3) And finally, newer levels will likely want to use newer dependencies like OpenZeppelin 2.x, which introduce breaking changes for contracts with old code. So, unless the code in these old contracts can be updated, Ethernaut's OpenZeppelin dependency has to remain at 1.x.

**Comment by frederickalcantara** [comment]
I'll take this issue on.

**Comment by frangio** [comment]
ZeppelinOS is no longer under development. :slightly_smiling_face:
