### ISSUE TITLE
Failed to create instance - Unhandled promise rejection 

### ISSUE THREAD

**Issue by sweatyc** [OpenZeppelin/ethernaut#99]
Sometime it failed to create the instance with error:
Unhandled promise rejection,Error: Cannot create instance of GatekeeperTwo; no code at address...

In Firefox:
![screen shot 2018-10-26 at 12 43 39 pm](https://user-images.githubusercontent.com/3059384/47539606-e0e1b480-d91c-11e8-8732-a2211164fe56.png)

In Chrome:
![screen shot 2018-10-26 at 12 49 05 pm](https://user-images.githubusercontent.com/3059384/47539765-9dd41100-d91d-11e8-98b5-c2b79a451316.png)

The contract is created with an address, but the FIrefox/Chrome console cannot read it.

For this example in Gatekeeper Two:
https://ropsten.etherscan.io/address/0xb7ebf9d78040a68a91c95ba38f8fd1ab921fbbf5

Some levels are able to create in first try, some levels (King, Gatekeeper Two) need try 3+ times until success.

**Comment by ajsantander** [comment]
Thanks for the report @sweatyc 

Indeed, this is a problem that we've been seeing a lot lately. I believe it has to do with Ropsten's latest crash. I added a work around that should work for the time being. Pls re-open otherwise!
